"""add embedding_vector to knowledge_chunks

Revision ID: 009_add_embedding_vector
Revises: 008_remove_enjaz_tables
Create Date: 2025-01-08 18:00:00.000000

This migration adds the 'embedding_vector' column to the 'knowledge_chunks' table
to store embeddings generated by sentence-transformers models.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite, postgresql

# revision identifiers, used by Alembic.
revision = '009_add_embedding_vector'
down_revision = '008_remove_enjaz_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add embedding_vector column to knowledge_chunks table."""
    # Add embedding_vector column as JSON
    # For SQLite: JSON type
    # For PostgreSQL: could use JSON or JSONB
    op.add_column(
        'knowledge_chunks',
        sa.Column('embedding_vector', sa.JSON(), nullable=True)
    )
    
    print("✅ Added 'embedding_vector' column to 'knowledge_chunks' table")


def downgrade() -> None:
    """Remove embedding_vector column from knowledge_chunks table."""
    op.drop_column('knowledge_chunks', 'embedding_vector')
    
    print("❌ Removed 'embedding_vector' column from 'knowledge_chunks' table")
