"""add_support_tickets_table

Revision ID: 6595bc39b441
Revises: 011_add_case_analysis_history
Create Date: 2025-11-03 10:13:42.425370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6595bc39b441'
down_revision = '011_add_case_analysis_history'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contracts_user_contract_id'), table_name='user_contracts')
    op.drop_table('user_contracts')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_contract_templates_template_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_index(op.f('idx_document_chunk'), table_name='legal_document_chunks')
    op.drop_index(op.f('ix_legal_document_chunks_article_number'), table_name='legal_document_chunks')
    op.drop_index(op.f('ix_legal_document_chunks_document_id'), table_name='legal_document_chunks')
    op.drop_index(op.f('ix_legal_document_chunks_id'), table_name='legal_document_chunks')
    op.drop_table('legal_document_chunks')
    op.drop_index(op.f('ix_contract_categories_category_id'), table_name='contract_categories')
    op.drop_table('contract_categories')
    op.drop_index(op.f('ix_user_favorites_favorite_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('favorite_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_index(op.f('ix_user_favorites_favorite_id'), 'user_favorites', ['favorite_id'], unique=False)
    op.create_table('contract_categories',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('name_ar', sa.VARCHAR(length=150), nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description_ar', sa.TEXT(), nullable=True),
    sa.Column('description_en', sa.TEXT(), nullable=True),
    sa.Column('legal_field', sa.VARCHAR(length=50), nullable=True),
    sa.Column('business_scope', sa.VARCHAR(length=50), nullable=True),
    sa.Column('complexity_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), nullable=True),
    sa.Column('color_code', sa.VARCHAR(length=7), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('template_count', sa.INTEGER(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['contract_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_contract_categories_category_id'), 'contract_categories', ['category_id'], unique=False)
    op.create_table('legal_document_chunks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('section_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('source_reference', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_document_chunks_id'), 'legal_document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_legal_document_chunks_document_id'), 'legal_document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_legal_document_chunks_article_number'), 'legal_document_chunks', ['article_number'], unique=False)
    op.create_index(op.f('idx_document_chunk'), 'legal_document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('contract_templates',
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('title_ar', sa.VARCHAR(length=200), nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description_ar', sa.TEXT(), nullable=True),
    sa.Column('description_en', sa.TEXT(), nullable=True),
    sa.Column('contract_structure', sqlite.JSON(), nullable=False),
    sa.Column('variables_schema', sqlite.JSON(), nullable=True),
    sa.Column('base_language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('requires_legal_review', sa.BOOLEAN(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('avg_rating', sa.INTEGER(), nullable=True),
    sa.Column('review_count', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['contract_categories.category_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_contract_templates_template_id'), 'contract_templates', ['template_id'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.INTEGER(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), server_default=sa.text("'other'"), nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'ar'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_processed', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_table('user_contracts',
    sa.Column('user_contract_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('contract_data', sqlite.JSON(), nullable=True),
    sa.Column('final_content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_contract_id')
    )
    op.create_index(op.f('ix_user_contracts_user_contract_id'), 'user_contracts', ['user_contract_id'], unique=False)
    # ### end Alembic commands ###
